### ISSUE TITLE
Add new planners to PDT

### ISSUE THREAD

**Issue by Liding-Zhang** [robotic-esp/pdt#1]
Dear PDT developers,

First of all, I would like to thank ESP Labs for your excellent work, this tool definitely will benefit ompl planner developers for their research, Appreciate it!

I'm currently trying to implement new ompl planners in PDT for visualizations, but I ran into problems. 
the specific information is as follows:

OS: Ubuntu 20.04 

ompl version: from robotic-esp , main branch,

pdt version: from robotic-esp , main branch,

the file that i modified: /ompl/pdt/src/factories/src/planner_factory.cpp

(yeah, i put pdt/ folder in ompl/ folder, for some reason that is the only scenario in that i can build pdt/ package.)

problem: After successfully including  xxxplanner.h file in planner_factory.cpp, i add a new case in the plannerFactory switch(along with the planner-> parameters etc..).
PS: i also create a json file in /ompl/pdt/parameters/defaults/planners
 and modified ompl/pdt/src/common/include/pdt/common/planner_type.h

naturally, i was trying to build the pdt package again, but during the visualization part( about 97%) the terminal abort the cmake --build and show the following error:

/usr/bin/ld: ../factories/libpdt_factories.a(planner_factory.cpp.o): in function `pdt::factories::PlannerFactory::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':
planner_factory.cpp:(.text+0x1230): undefined reference to `ompl::geometric::xxxxx::xxxxxx(std::shared_ptr<ompl::base::SpaceInformation> const&, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/experiments/CMakeFiles/benchmark.dir/build.make:115: bin/benchmark] Error 1
make[1]: *** [CMakeFiles/Makefile2:741: src/experiments/CMakeFiles/benchmark.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
 
since the new xxxxplanner can be used in ompl.app GUI and for benchmarks, so i guess the planner file are fine... 

could you please help me with this issue or provide step-by-step instructions regarding adding new planners in PDT..

Once Again, Thanks for your work! 
Best Regards,
Liding Zhang

**Comment by marlinstrub** [comment]
Hi @Ecurbliz I'm glad you find our work useful.

From your description, it sounds like there might be something wrong with your installation of OMPL. How did you install it?

**Comment by Liding-Zhang** [comment]
> Hi @Ecurbliz I'm glad you find our work useful.
> 
> From your description, it sounds like there might be something wrong with your installation of OMPL. How did you install it?

Hii Marlin,

 i installed ompl by **git clone** from https://github.com/robotic-esp/ompl.git and **mkdir a build/ folder** along with **cmake --build** in the build/

would that be a problem? i also installed from **./install-ompl-ubuntu.sh --app** once, but it's in a totally different path than the git clone version.

PS: in my /usr/local/include , there are two ompl folder, ompl-1.5 and ompl-1.6

thanks for your reply and looking forward to hearing from you again!

best regards,
Liding

**Comment by Liding-Zhang** [comment]
> Hi @Ecurbliz I'm glad you find our work useful.
> 
> From your description, it sounds like there might be something wrong with your installation of OMPL. How did you install it?

I'm closing this issue because i was solved by installing ompl into usr/local.

you are absolutely correct!!!

the command that I'm using is **sudo cmake --install build/Release**( install ompl into usr/local)

and then build PDT package, it works.
thanks for your help! Marlin,

Best regards,
Liding Zhang

**Comment by marlinstrub** [comment]
You are very welcome, good to hear you were able to solve your problem.

PS: If you have two different OMPL installations and need to build PDT with a specific one, you can use the option `PDT_OMPL_DIR` in the `cmake` step: `cmake -DPDT_OMPL_DIR=/path/to/desired/ompl/version ..`.

**Comment by Liding-Zhang** [comment]
> You are very welcome, good to hear you were able to solve your problem.
> 
> PS: If you have two different OMPL installations and need to build PDT with a specific one, you can use the option `PDT_OMPL_DIR` in the `cmake` step: `cmake -DPDT_OMPL_DIR=/path/to/desired/ompl/version ..`.

Got it! you are the best ;)
