### ISSUE TITLE
Different  version of new algorithm visualization in interactive visualizer

### ISSUE THREAD

**Issue by liangxu1109** [robotic-esp/pdt#2]
Hi, Marlin! I have recently been using PDT to test the algorithm I developed in OMPL. Specifically, I've used the "random rectangles 2D" context. However, since the obstacles are random, I'm unable to test my new algorithm against other algorithms on the same map in visulization. I noticed in your paper's video that you've compared different algorithms on the same random rectangle 2D scenario. Could you please explain how you managed to do that?

**Comment by marlinstrub** [comment]
Hi @liangxu1109! You should just be able to add a `"seed": 1234` key-value pair to the `experiment` section of your visualization config file. The seed number  defines the obstacle generation. Let me know if this doesn't work for you.

**Comment by liangxu1109** [comment]
Thanks! solved!
